version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: company_similarity_service
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://user:password@postgres:5432/company_db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: ankane/pgvector:v0.5.0  # Pre-built image with pgvector
    container_name: postgres_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=company_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
